name: Build and Version

on: [push, workflow_dispatch]

env:
  BUILD_DATE: ${{ github.run_number }}  # Auto-incremented per run
  GIT_TAG: ${{ github.ref_name }}      # Gets tag if available

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git history
    
    # Auto-detect version (tag-based or date-based)
    - name: Determine Version
      id: version
      run: |
        # Use git tag if available (format: v1.0.0)
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Using tagged version: $VERSION"
        else
          # Dev build format: 1.0.YYYYMMDD.BUILD_NUM
          VERSION="1.0.$(date +'%Y%m%d').$BUILD_DATE"
          echo "Using dev version: $VERSION"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=${VERSION}.0" >> $GITHUB_ENV
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Build with version info
    - name: Build
      run: |
        dotnet build -c Release `
          /p:Version=$env:VERSION `
          /p:FileVersion=$env:VERSION `
          /p:AssemblyVersion=$env:ASSEMBLY_VERSION `
          /p:InformationalVersion=$env:VERSION-$env:GITHUB_SHA
        
    - name: Publish
      run: |
        dotnet publish -c Release -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:Version=$env:VERSION
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpotifyPreventLock-${{ env.VERSION }}
        path: |
          bin/Release/net8.0-windows/win-x64/publish/SpotifyPreventLock.exe
          bin/Release/net8.0-windows/win-x64/publish/SpotifyPreventLock.pdb
