name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Simple version detection
    - name: Get Version
      id: get_version
      run: |
        $version = "1.0.$env:GITHUB_RUN_NUMBER"
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "Using version: $version"
    
    - name: Build
      run: |
        dotnet build -c Release `
          /p:Version=$env:VERSION `
          /p:FileVersion=$env:VERSION `
          /p:AssemblyVersion=$env:VERSION.0
        
    - name: Publish
      run: |
        dotnet publish -c Release -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpotifyPreventLock-${{ env.VERSION }}
        path: bin/Release/net8.0-windows/win-x64/publish/SpotifyPreventLock.exe
