name: Build SpotifyPreventLock
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Build Release
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: SpotifyPreventLock.exe
        path: bin/Release/net6.0/win-x64/publish/SpotifyPreventLock.exe
